### ISSUE TITLE
How do I build this project?

### ISSUE THREAD

**Issue by jarrodu** [M4sterVad/CBMT#1]
I am interested in building your app, and installing it on my Android device. Are there any directions for how to do this?

**Comment by M4sterVad** [comment]
Hi jarrodu,

sadly this project runs on an older version of react native. You could try to upgrade the project to a new version and then try to bundle it so you can generate the apk. There might also a solution hoe bundle the project on version 0.57.8.

BG Vadim

**Comment by jarrodu** [comment]
Great. Thanks for the information. How about the license?

**Comment by M4sterVad** [comment]
I will add a non-commercial licence to this project asap.
